p8105_hw2_xc2859
================
Xiaoxue Cui
2026-10-05

# Problem 1

**Read and clean the data**

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
nycsubway_df = 
  read.csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", 
    na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  select(line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entrance_type, entry, vending, ada) |>
  mutate(
    entry = case_match(
      entry, 
      "YES" ~ TRUE, 
      "NO" ~ FALSE
    )
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

The dataset contains information on subway lines, stations, and station
entrances. Variables include `line`, `station_name`, `station_latitude`,
`station_longitude`, routes served (`route1` to `route11`), `entry`
(whether the entrance allows entry into the station), `vending` (vending
machine availability), `entrance_type`, as well as `ada` (ADA
compliance). For data cleaning, I first cleaned the variable names by
using `clean_names` function, then selected the variables needed for the
analysis by using `select` function, and finally converting `entry` from
a character variable to a logical variable by applying `mutate` and
`case_match` functions. The resulting dataset has 1868 rows and 19
columns. These data are not tidy because information on routes served
are stored in multiple columns instead of in separate route number and
route name variables.

**Answer the questions**

``` r
# How many distinct stations are there?
nycsubway_df |> 
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 465

``` r
# How many stations are ADA compliant?
nycsubway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

``` r
# What proportion of station entrances / exits without vending allow entrance?
nycsubway_df |>
  filter(vending == "NO") |>
  pull(entry) |> 
  mean()
```

    ## [1] 0.3770492

Therefore, there are 465 distinct stations. 84 stations are ADA
compliant. There are about 37.70% station entrances / exits without
vending allow entrance.

**Reformat data**

``` r
nycsubway_df = 
  nycsubway_df |> 
  mutate(
    across(route1:route11, as.character)
  )

nycsubway_tidy_df = 
  nycsubway_df |>
  pivot_longer(
    route1:route11, 
    names_to = "route_number", 
    names_prefix = "route", 
    values_to = "route_name", 
    values_drop_na = TRUE
  )

# Number of distinct stations that serve the A train
nycsubway_tidy_df |>
  filter(route_name == "A") |>
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 60

``` r
# Of the stations that serve the A train, how many are ADA compliant?
nycsubway_tidy_df |>
  filter(
    route_name == "A", 
    ada == TRUE) |>
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 17

There are 60 distinct stations that serve the A train. Of the stations
that serve the A train, 17 are ADA compliant.

# Problem 2

**Create a tidy dataset**

``` r
# Read and clean the Mr.Trash Wheel sheet
MrTrash_df = 
  readxl::read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx", 
    sheet = "Mr. Trash Wheel", 
    range = "A2:N709") |> 
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    sports_balls = 
      as.integer(round(sports_balls)), 
    trash_wheel_name = "Mr. Trash Wheel", 
    year = as.integer(year)
  )

# Read and clean the Professor Trash Wheel sheet
ProfessorTrash_df = 
  readxl::read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx", 
    sheet = "Professor Trash Wheel", 
    range = "A2:M135") |>
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel_name = "Professor Trash Wheel", 
    year = as.integer(year)
  )

# Read and clean the Gwynnda sheet
Gwynns_df = 
   readxl::read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx", 
    sheet = "Gwynns Falls Trash Wheel", 
    range = "A2:L351") |>
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(
    trash_wheel_name = "Gwynns Falls", 
    year = as.integer(year)
  )

# Combine these sheets into a tidy dataset
trashwheel_tidy_df = 
  bind_rows(MrTrash_df, ProfessorTrash_df, Gwynns_df) |>
  select(trash_wheel_name, everything())
```

**Data description**

The combined Trash Wheel dataset contains 1188 observations and 15
variables. These variables include the Trash Wheel name, dumpster
number, collection date, trash weight and volume, counts of different
types of trash such as polystyrene waste, plastic bottles, cigarette
butts, glass bottles and plastic bags, as well as estimated number of
homes that could be powered by the collected trash.

``` r
# total weight of trash collected by Professor Trash Wheel
trashwheel_tidy_df |>
  filter(trash_wheel_name == "Professor Trash Wheel") |> 
  pull(weight_tons) |>
  sum(na.rm = TRUE)
```

    ## [1] 282.26

``` r
# total number of cigarette butts collected by Gwynnda in June of 2022
trashwheel_tidy_df |> 
  filter(
    trash_wheel_name == "Gwynns Falls", 
    month == "June", 
    year == 2022
  ) |> 
  pull(cigarette_butts) |> 
  sum(na.rm = TRUE)
```

    ## [1] 18120

For available data, the total weight of trash collected by Professor
Trash Wheel was 282.26 tons. The total number of cigarette butts
collected by Gwynnda in June of 2022 was 18120.

# Problem 3

**Import, clean, and tidy the baseline demographics dataset**

``` r
baseline_df = 
  read.csv(
    "data_mci/MCI_baseline.csv", 
    skip = 1, 
    na = c(".", "NA", "")) |>
  janitor::clean_names() |>
  filter(
    is.na(age_at_onset) | age_at_onset > current_age
  ) |>
  mutate(
    sex = case_match(
      sex, 
      0 ~ "female", 
      1 ~ "male"
    ), 
    apoe4 = case_match(
      apoe4, 
      0 ~ "non-carrier", 
      1 ~ "carrier"
    )
  )
```

**Describe the import process and dataset features**

The baseline demographics dataset was imported using `read.csv`, with
the first row skipped because it contains notes on how the variable was
coded rather than meaningful data, `"."`, `"NA"` and blank entries were
treated as missing values during import. Variable names were cleaned
using `clean_names`. Participants who had MCI onset at baseline were
excluded by retaining those who either had no recorded age at MCI onset
or developed MCI after their current age. The numeric codes for
variables `sex` and `apoe4` were recoded as `female`/ `male` and
`non-carrier` / `carrier`, respectively. The resulting dataset has 479
observations and 6 variables. These variables contains information about
participants’ demographics at baseline level, including participant ID,
current age, sex, years of education, APOE4 carrier status, and age at
MCI onset (missing data for this variable represents that a subject
remains MCI-free during the follow-up period).

**Baselne characteristics**

``` r
# Among recruited participants, the number of those develop MCI
baseline_df |>
  filter(
    !is.na(age_at_onset)) |>
  nrow()
```

    ## [1] 93

``` r
# Average baseline age
baseline_df |> 
  pull(current_age) |>
  mean() |> 
  round(digits = 2)
```

    ## [1] 65.03

``` r
# Proportion of women who are APOE4 carriers
baseline_df |> 
  filter(sex == "female") |>
  mutate(
    apoe4 = case_match(
      apoe4, 
      "carrier" ~ TRUE, 
      "non-carrier" ~ FALSE
    )
  ) |>
  pull(apoe4) |>
  mean() 
```

    ## [1] 0.3

There were 479 participants recruited. Of those recruited, 93
participants developed MCI. The average baseline age is 65.03. 30% of
women in the study are APOE4 carriers.

**Import, clean, and tidy the dataset of longitudinally observed
biomarker values**

``` r
longitudinal_df = 
  read.csv(
    "data_mci/mci_amyloid.csv", 
    skip = 1, 
    na = c(".", "NA", "")) |>
  janitor::clean_names() |> 
  pivot_longer(
    baseline:time_8, 
    names_to = "time_years", 
    values_to = "value"
  ) |> 
  mutate(
    time_years = recode_values(
      time_years, 
      "baseline" ~ 0, 
      "time_2" ~ 2, 
      "time_4" ~ 4, 
      "time_6" ~ 6, 
      "time_8" ~ 8
    )
  )
```

**Describe the import process and dataset features**

The longitudinal amyloid value dataset was imported using `read.csv`,
with the first row skipped since it did not contain information about
the data. `"."`, `"NA"` and blank entries were treated as missing values
during import, and variable names were cleaned using `clean_names`. The
repeated biomarker measurements, originally stored in separate columns
for baseline and follow-up visits, were reformatted using
`pivot_longer`. The visit variable was then recoded as `time_years`,
with 0 representing baseline and 2, 4, 6, and 8 representing years
elapsed since the study baseline. The resulting dataset is now tidy. Key
variables include participant ID, time in years passed since the
baseline time, and the corresponding results of amyloid β 42/40 ratio
measurement (called `values`).

**Check participants appear in only one dataset**

``` r
# Participants only in the baseline dataset
baseline_df |>
  anti_join(
    longitudinal_df |> distinct(study_id), 
    by = c("id" = "study_id")
  ) |> 
  nrow()
```

    ## [1] 8

``` r
# Participants only in the longitudinal dataset
longitudinal_df |>
  distinct(study_id) |>
  anti_join(
    baseline_df, 
    by = c("study_id" = "id")
  ) |>
  nrow()
```

    ## [1] 16

There were 8 participants who only appeared in the baseline dataset, and
16 participants who only appeared in the longitudinal dataset.

**Combine the two datasets**
